name: Daily netlify deploy
on:
  schedule:
    - cron:  '26 14 * * *' # every day, utc 
  push:
    branches: 
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Trigger Netlify build webhook
      env:
        NETLIFY_WEBHOOK_URL: ${{ secrets.NETLIFY_WEBHOOK_URL }}
      run: curl -X POST -d {} "$NETLIFY_WEBHOOK_URL"
