name: Daily netlify deploy
on:
  schedule:
    - cron:  '00 12 * * *' # every day, utc

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Trigger Netlify build webhook
      env:
        WEBHOOK_URL: ${{ secrets.NETLIFY_WEBHOOK_URL }}
      run: curl -X POST -d {} "$WEBHOOK_URL"
