name: Daily netlify deploy
on:
  schedule:
    - cron:  '20 14 * * *' # every day, utc 

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Trigger Netlify build webhook
      env:
        NETLIFY_WEBHOOK_URL: ${{ secrets.SECRET_TOKEN }}
      run: curl -X POST -d {} "$NETLIFY_WEBHOOK_URL"
