name: Daily netlify deploy
on:
  schedule:
    - cron:  '00 12 * * *' # every day, utc 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    # We don't need to build here, just trigger our netlify build task
    - run: curl -X POST -d {} $NETLIFY_WEBHOOK_URL
