name: Daily Deploy
on:
  schedule:
    - cron:  '00 9 * * *' # every day, utc
  workflow_dispatch: # Allows us to run job manually

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Trigger Netlify build
      env:
        WEBHOOK_URL: ${{ secrets.NETLIFY_WEBHOOK_URL }}
      run: curl -X POST -d {} "$WEBHOOK_URL" --fail
